blog/urls.py
from blog.views import PostLV
from django.conf.urls import url

urlpatterns = [
    url(r'^post/$', PostLV.as_view(), name='post_list')
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from bookmark.views import BookmarkLV, BookmarkDV
from mysite.views import HomeView, BookmarkView

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', HomeView.as_view(), name='home'),

    url(r'^bookmark/$', BookmarkLV.as_view(), name='index'),
    url(r'^bookmark/(?P<pk>\d+)/$', BookmarkDV.as_view(), name='detail'),

    url(r'blog/', include('blog.urls', namespace='blog')),

    url(r'^photo/', include('photo.urls', namespace='photo')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

photo/urls.py
from django.conf.urls import url
from photo.views import *

urlpatterns = [

    url(r'^$', AlbumLV.as_view(), name='index'),


]

blog/models.py
from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.
class Post(models.Model) :
    title = models.CharField('TITLE', max_length=50)
    image = models.ImageField(blank=True)
    slug = models.SlugField('SLUG', unique=True, allow_unicode=True, help_text='one word for title alias')
    description = models.CharField('DESCRIPTION', max_length=100, blank=True, help_text='simple description text')
    content = models.TextField('CONTENT',)
    create_date = models.DateTimeField('Create Date', auto_now_add=True)
    modify_date = models.DateTimeField('Modify Date', auto_now=True)

    class Meta :
        verbose_name = 'post'
        verbose_name_plural = 'posts'
        db_table = 'my_post'
        ordering = ('modify_date',)

    def __str__(self):
        return self.title

bookmark/models.py
from django.db import models

# Create your models here.

class Bookmark(models.Model):
    title = models.CharField(max_length=100, blank=True, null=True)
    url = models.URLField('url', unique=True)
    create_date = models.DateTimeField('Create Date', auto_now_add=True,
                                       blank=True, null=True)
    modify_date = models.DateTimeField('Modify Date', auto_now=True,
                                       blank=True, null=True)

    def __str__(self):
        return self.title

photo/models.py
from django.db import models
from django.core.urlresolvers import reverse
from photo.fields import ThumbnailImageField


# Create your models here.
class Album(models.Model) :
    name = models.CharField(max_length=50)
    description = models.CharField('One Line Description',
                                   max_length=100, blank=True)

    class Meta :
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('photo:album_detail', args=(self.id,))

class Photo(models.Model) :
    album = models.ForeignKey(Album)
    title = models.CharField(max_length=50)
    image = ThumbnailImageField(upload_to='photo/%y/$m')
    description = models.TextField('Photo Description', blank=True)
    upload_date = models.DateTimeField('Upload Date', auto_now_add=True)

    class Meta :
        ordering = ['title']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('photo:photo_detail', args=(self.id,))

blog/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from blog.models import Post

# Create your views here.

class PostLV(ListView) :
    model = Post
    context_object_name = 'posts'

bookmark/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from bookmark.models import Bookmark
# Create your views here.

class BookmarkLV(ListView):
    model = Bookmark

class BookmarkDV(DetailView):
    model = Bookmark

mysite/views.py
from django.views.generic.base import TemplateView

class HomeView(TemplateView):
    template_name = 'main.html'

class BookmarkView(TemplateView):
    template_name = ""

photo/views.py
from django.shortcuts import render
from photo.models import Album, Photo
from django.views.generic import ListView

# Create your views here.

class AlbumLV(ListView) :
    model = Album

blog/templates/blog/post_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load staticfiles %}
    <link href="https://fonts.googleapis.com/css?family=Nanum+Gothic|Pattaya&display=swap" rel="stylesheet"><link href="https://fonts.googleapis.com/css?family=Nanum+Gothic|Pattaya&display=swap" rel="stylesheet">

    <style>

        .box{
            width:400px; height:auto;
            border:1px solid lightgray;
            display:inline-block;
            border-radius:5px;
            margin-left:50px; margin-bottom:20px;
        }
        img{
            width:380px; height:380px;
            margin:auto; display:block;
        }
        p{
            font-family: 'Nanum Gothic', sans-serif;
            font-size: 19px;
            padding-left: 20px;
            padding-right: 20px;
        }
        .d{
            height:100px;
        }
        .box_title{
            text-align: center;
            margin: 10px;
            font-size: 30px;
            color: orangered;
            font-family: 'Pattaya', sans-serif;
        }
        #title{
            font-family: 'Pattaya', sans-serif;
            text-align: center;
            font-size:130px;
        }
        #title_mini{
            font-size:30px;
            color:dimgray;
        }
        .label{
            font-family: 'Pattaya', sans-serif;

        }

    </style>

</head>
<body>
    <h1 id="title">Blog <span id="title_mini">made with Django</span></h1>

    {% for post in posts %}
        <div class="box">
            <p class="box_title">{{ post.title }}</p>
            <div class="imgBox">
                <img src="{{ post.image.url }}">
            </div>
            <p class="d"><span class="label">Description</span>{{ post.description }}</p>
            <p><span class="label">Create Date</span>{{ post.create_date }}</p>
            <p><span class="label">Modify Date</span>{{ post.modify_date }}</p>
        </div>
    {% endfor %}

</body>
</html>

bookmark/templates/bookmark/bookmark_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>bookmark detail</title>
    <style>
        #content{
            width:900px;
            margin: auto;
            text-align:center;
            font-size:30px;
            font-family: 'Nanum Gothic', sans-serif;
        }

        ul{
            list-style: none;
            font-family: 'Nanum Gothic', sans-serif;
        }
        li{
            width: 900px;
            margin: auto;
            text-align: left;
            margin-bottom: 30px;
        }
        li:hover{
            background-color: rgba(255, 20, 147, 0.1);
        }

        a{
            text-decoration: none;
            color: dimgray;
        }

        h1{
            font-family: 'DM Sans', sans-serif;
        }

        #title{
            font-size: 80px;
            color: red;
        }

        .small{
            font-size: 40px;
            color: dimgray;
        }

        iframe{
            width: 900px;
            height: 506px;
        }


    </style>
</head>
<body>
    <div id="content">
        <h1 id="title">{{ object.title }}</h1>

        <ul>
            <li>URL: <a href="{{ object.url }}" target="_blank">
                {{ object.url }}
            </a></li>
            <li>Create Date : {{ object.create_date }}</li>
            <li>Modify Date : {{ object.modify_date }}</li>
        </ul>

        <iframe src="{{ object.url }}"></iframe>

    </div>

</body>
</html>

bookmark/templates/bookmark/bookmark_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>bookmark list</title>

    <link href="https://fonts.googleapis.com/css?family=DM+Sans|Nanum+Gothic&display=swap" rel="stylesheet">

    <style>

        #content{
            width:900px;
            margin: auto;
            text-align:center;
            font-size:30px;
            font-family: 'Nanum Gothic', sans-serif;
        }

        ul{
            list-style: none;
            font-family: 'Nanum Gothic', sans-serif;
        }
        li{
            width: 500px;
            margin: auto;
            text-align: left;
            margin-bottom: 30px;
        }
        li:hover{
            background-color: rgba(255, 20, 147, 0.1);
        }

        a{
            text-decoration: none;
            color: dimgray;
        }

        h1{
            font-family: 'DM Sans', sans-serif;
        }

        #title{
            font-size: 80px;
            color: red;
        }

        .small{
            font-size: 40px;
            color: dimgray;
        }

    </style>

</head>
<body>
    <div id="content">
        <h1 id="title">
            F<span class="small">avorite</span> Y<span class="small">outube</span> L<span class="small">ist</span>
        </h1>

        <ul>
            {% for bookmark in object_list %}
            <li><a href="{% url 'detail' bookmark.id %}">{{ bookmark }}</a></li>
            {% endfor %}
        </ul>



    </div>
</body>
</html>

photo/templates/photo/album_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>album_list</title>
</head>
<body>

{% load staticfiles %}
{% for item in object_list %}
    {% for photo in item.photo_set.all %}
        <img class ="thumbnail" src="{{ photo.image.thumb_url }}">
    {% endfor %}
{% endfor %}

</body>
</html>

templates/home.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>main page</title>
    <link href="https://fonts.googleapis.com/css?family=Pattaya|Sunflower:300" rel="stylesheet">
    <style>
        body{
            background-image: url("{% static 'img/Leaves.png' %}");
            background-repeat: no-repeat;
            background-size: 100%;
            background-position: center top;
        }
        #subject{
            font-size: 100px;
            text-align: center;
            color: orangered;
            font-family: 'Pattaya', sans-serif;
        }
        #title{
            font-size: 150px;
            text-align: center;
            color: forestgreen;
            font-family: 'Pattaya', sans-serif;
            background-color: rgba(0, 255, 191, 0.1);
        }
        #made{
            font-size: 50px;
            text-align: center;
            color: darkgray;
            font-family: 'Pattaya', sans-serif;
        }
        .big{
            color: darkslategray;
        }
        ul li{
            display: inline-block;
            font-size: 25px;
            font-family: 'Pattaya', sans-serif;
            color: orangered;
            border: 5px double orange;
            border-radius: 10px;
            margin: 20px 15px;
            padding: 5px;
        }
        ul{
            text-align: center;
            background-color: rgba(230, 255, 247, 0.5);
        }
        a{
            text-decoration: none;
            color: orangered;
        }
    </style>
</head>
<body>
    <h1 id="subject">DM4 WEB SERVICE MAKER</h1>
    <h1 id="title">Django Framework</h1>
    <p id="made">Made by <span class="big">F</span>uking <span class="big">W</span>orld</p>

    <ul>
        <li><a href="{% url 'index' %}" target="_blank">Bookmark</a></li>
        <li><a href="{% url 'blog:post_list' %}" target="_blank">Blog</a></li>
        <li><a href="">Photo</a></li>
    </ul>
</body>
</html>

templates/main.html
<!DOCTYPE html>
<html>
    <head>
        {% load staticfiles %}

        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        
        <title></title>
        
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">

        <!-- Optional theme -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap-theme.min.css" integrity="sha384-6pzBo3FDv/PJ8r2KRkGHifhEocL+1X2rVCTTkUfGk7/0pbek5mMa1upzvWbrUbOZ" crossorigin="anonymous">

        <!-- Latest compiled and minified JavaScript -->
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script>
        
        <link href="https://fonts.googleapis.com/css?family=DM+Sans|Nanum+Gothic&display=swap" rel="stylesheet">

        <!-- jQuery library -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

        <!-- Latest compiled JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
        
        <style>
            
            .bg-1{
                background-color: rgb(26, 188, 156);
                color: white;
            }
            
            .bg-2{
                background-color: rgb(71, 78, 93);
                color: white;
            }
            
            .bg-3{
                background-color: white;
                color: rgb(85, 85, 85);
            }
            
            .bg-4{
                background-color: rgb(85, 85, 85);
            }
            
            .container-fluid{
                padding-top: 70px;
                padding-bottom: 70px;
            }
            
            .link{
                text-decoration: none;
                color: orangered;
            }
            .link:hover{
                text-decoration: none;
                color: white;
            }
            
            body{
                font-family: 'DM Sans', sans-serif;
                font-size: 20px;
                line-height: 1.8;
            }
            p{
                font-size: 16px;
            }
            #myNavbar{
                font-size: 14px;
            }

            .kor{
                font-family: 'Nanum Gothic', sans-serif;
            }
            
        </style>
    </head>
    
    <body>
       
       <nav class="navbar navbar-default">
           <div class="container">
               <div class="navbar-header">
                   <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                       <span class="icon-bar"></span>
                       <span class="icon-bar"></span>
                       <span class="icon-bar"></span>
                   </button>
                   <a href="#" class="navbar-brand">DH.S</a>
               </div>
               <div class="collapse navbar-collapse" id="myNavbar">
                  <ul class="nav navbar-nav navbar-right">
                      <li><a href="{% url 'admin:index' %}">ADMIN</a></li>
                      <li><a href="#">SIGN UP</a></li>
                      <li><a href="#">SIGN IN</a></li>
                      <li><a href="#">SIGN OUT</a></li>
                  </ul>
               </div>
           </div>
       </nav>
        
        <div class="container-fluid bg-1 text-center">
            <h3>DLAB WEB SERVICE MAKER</h3>
            <img src="{% static 'img/dog_1.jpg' %}" alt="dog" width="250px" height="250px"
            class="img-circle">
            <h3>HTML &amp; CSS &amp; PYTHON &amp; DJANGO PROJECT</h3>
        </div>
        <div class="container-fluid bg-2 text-center">
            <h3>INTRODUCE PROJECT</h3>
            <p>Lorem... ipsum...</p>
            <a href="#" class="btn btn-default btn-lg">
            <span class="glyphicon glyphicon-search"></span> Search</a>
        </div>


        <div class="container-fluid bg-3 text-center">
            <h3>WEB SERVICE PROJECT</h3>
            <p class="kor">Python과 HTML/CSS 그리고 Bootstrap을 활용한 프로젝트</p>
            <div class="row">
                <div class="col-sm-4">
                    <p>Lorem ipsum</p>
                    <img src="{% static 'img/dog_2.jpg' %}" alt="dog" class="img-responsive" style="width:100%">
                </div>
                <div class="col-sm-4">
                    <p>Favorite Youtube list</p>
                    <a href="{% url 'index' %}" target="_blank">
                        <img src="{% static 'img/youtube_logo.png' %}" alt="youtube logo" class="img-responsive" style="width:100%">
                    </a>
                </div>
                <div class="col-sm-4">
                    <p>Blog made with django</p>
                    <a href="{% url 'blog:post_list' %}" target="_blank"><img src="{% static 'img/dog_4.jpg' %}" alt="dog" class="img-responsive" style="width:100%"></a>
                </div>
            </div>
        </div>
        
        <div class="container-fluid bg-3 text-center">
            <h3>PYTHON PROJECT</h3>
            <p>Lorem... ipsum...</p>
            <div class="row">
                <div class="col-sm-4">
                    <p>Lorem ipsum</p>
                    <img src="{% static 'img/dog_2.jpg' %}" alt="dog" class="img-responsive" style="width:100%">
                </div>
                <div class="col-sm-4">
                    <p>Lorem ipsum</p>
                    <img src="{% static 'img/dog_3.jpg' %}" alt="dog" class="img-responsive" style="width:100%">
                </div>
                <div class="col-sm-4">
                    <p>Lorem ipsum</p>
                    <img src="{% static 'img/dog_4.jpg' %}" alt="dog" class="img-responsive" style="width:100%">
                </div>
            </div>
        </div>
        
        <div class="container-fluid bg-3 text-center">
            <h3>RASPBERRY PI PROJECT</h3>
            <p>Lorem... ipsum...</p>
            <div class="row">
                <div class="col-sm-4">
                    <p>Lorem ipsum</p>
                    <img src="{% static 'img/dog_2.jpg' %}" alt="dog" class="img-responsive" style="width:100%">
                </div>
                <div class="col-sm-4">
                    <p>Lorem ipsum</p>
                    <img src="{% static 'img/dog_3.jpg' %}" alt="dog" class="img-responsive" style="width:100%">
                </div>
                <div class="col-sm-4">
                    <p>Lorem ipsum</p>
                    <img src="{% static 'img/dog_4.jpg' %}" alt="dog" class="img-responsive" style="width:100%">
                </div>
            </div>
        </div>
        
        <footer class="container-fluid bg-4 text-center">
            <p>Bootstrap Design Made By <a href="http://www.daddyslab.com/" class="link" target="_blank"><b>DLAB</b></a></p>
        </footer>
        
    </body>
</html>